package com.example.crfcavemonitor.ui.report

data class SpeciesOption(val name: String, val id: Int)

val allSpecies = listOf(
    SpeciesOption("Ozark Big-eared Bat", 2),
    SpeciesOption("Big Brown Bat", 3),
    SpeciesOption("Gray Bat", 8),
    SpeciesOption("Small footed Bat", 9),
    SpeciesOption("Little Brown Bat", 10),
    SpeciesOption("Northern Bat", 11),
    SpeciesOption("Indiana Bat", 12),
    SpeciesOption("Myotis sp. Bat", 13),
    SpeciesOption("Pipistrelle Bat", 21),
    SpeciesOption("Unidentified Bat", 30),
    SpeciesOption("Bat Guano Area", 0),

    SpeciesOption("Green/bronze frog", 111),
    SpeciesOption("Pickerel frog", 112),
    SpeciesOption("Long-tailed salamander", 130),
    SpeciesOption("Long-tailed salamander", 130),
    SpeciesOption("dark sided salamander", 130),
    SpeciesOption("cave salamander", 132),
    SpeciesOption("W. Grotto salamander", 134),
    SpeciesOption("N. Grotto salamander", 136),
    SpeciesOption("S. Grotto salamander", 137),
    SpeciesOption("slimy salamander", 141),
    SpeciesOption("zigzag salamander", 140),
    SpeciesOption("red backed", 142),
    SpeciesOption("Unidentified salamander larva", 133),

    SpeciesOption("Camel cricket", 3089),
    SpeciesOption("Ptomaphagus beetle", 2095),
    SpeciesOption("Rove beetle", 2180),
    SpeciesOption("Ground beetle", 1875),
    SpeciesOption("Heleomyzid fly", 2594),
    SpeciesOption("Spelobia fly", 2678),
    SpeciesOption("mosquito", 2558),
    SpeciesOption("mycet gnat", 2621),
    SpeciesOption("Gen mosquito or gnat", 2720),
    SpeciesOption("Dipluran", 1520),
    SpeciesOption("Pygmarrhopalites springtail", 1608),
    SpeciesOption("Generic springtail", 1797),
    SpeciesOption("Webworm", 2600),
    SpeciesOption("Herald moth", 3012),
    SpeciesOption("Other moth", 3040),
    SpeciesOption("Crane Fly", 2705),

    SpeciesOption("Raccoon", 53),
    SpeciesOption("Wood rat", 67),
    SpeciesOption("White-footed or deer mouse", 70),

    SpeciesOption("White amphipod", 444),
    SpeciesOption("Pigmented amphipod", 445),
    SpeciesOption("Salem cave crayfish", 463),
    SpeciesOption("Bristly cave crayfish", 464),
    SpeciesOption("Other crayfish", 480),
    SpeciesOption("Troglomorphic (white) isopod", 521),
    SpeciesOption("Other aquatic isopod", 495),
    SpeciesOption("terrestrial isopod sowbug", 499),
    SpeciesOption("aquatic cave snail", 639),
    SpeciesOption("slug", 710),
    SpeciesOption("Generic aquatic snail", 711),
    SpeciesOption("terrestrial snail", 712),
    SpeciesOption("dark flatworm/planaria", 3250),
    SpeciesOption("white flatworm", 3237),

    SpeciesOption("Phoebe", 390),
    SpeciesOption("Turkey vulture", 377),

    SpeciesOption("Ozark cave fish", 330),
    SpeciesOption("Southern cave fish", 332),
    SpeciesOption("banded sculpin", 336),
    SpeciesOption("mottled sculpin", 338),
    SpeciesOption("grotto sculpin", 340),
    SpeciesOption("carp", 303),

    SpeciesOption("White millipede", 919),
    SpeciesOption("Pigmented mill.", 920),
    SpeciesOption("crazy legs mite", 1109),
    SpeciesOption("other mite", 1130),
    SpeciesOption("Fishing spider", 1281),
    SpeciesOption("Meta spider", 1294),
    SpeciesOption("Generic spider", 1321),
    SpeciesOption("Pseudoscorpion", 1429),
    SpeciesOption("Leiobunum harvestman", 1387)
)